FROM python:3.11-alpine3.20

WORKDIR /app
COPY . .
RUN apk update && apk add tzdata
RUN pip install -r requirements.txt

ENV TELEGRAM_TOKEN=abc
ENV TELEGRAM_ADMIN=abc
ENV TELEGRAM_GROUP=abc
ENV TELEGRAM_THREAD=1
ENV TELEGRAM_NOTIFICATION_CHANNEL=abc
ENV CHECK_UPDATES=0
ENV CHECK_UPDATE_EVERY_HOURS=4
ENV CONTAINER_NAME=abc
ENV BUTTON_COLUMNS=2
ENV LANGUAGE=EN
ENV EXTENDED_MESSAGES=0
ENV TZ=UTC

ENTRYPOINT ["python", "docker-controller-bot.py"]
